### ISSUE TITLE
Preview window doesn't recognize keyboard input

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/repl-legacy#11]
Maybe this helps https://stackoverflow.com/questions/1199075/keydown-event-on-a-iframe

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Under linux + firefox I have the games samples working (mario + ozmo).

But of course you need to click, in the iframe/canvas to give focus to the iframe window so it can capture the keyboard events.

And yes, we could probably allow the iframe to listen to keyevents from the parent window but not sure of the drawbacks here.

**Comment by alfonsogarciacaro** [comment]
Ah, ok. So you need to click the iframe, didn't thought of that 😅 Maybe we can add a message to warn users as silly as me :wink:

**Comment by alfonsogarciacaro** [comment]
Anyway, that should be enough for now. Thanks a lot for checking, I'll close the issue :+1:
