### ISSUE TITLE
Collapse left menu

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/repl-legacy#14]
The up arrow next to "Samples" is not working for me. It'd be nice to collapse the left menu when you need more space.

**Comment by ncave** [comment]
+1 to collapsible samples menu and also collapsible right panel (the generated code / live panel) for more space. Alternatively, moving the samples to the toolbar above, possibly in different categories?

**Comment by MangelMaxime** [comment]
Yes, I was planning to add the collapse to the left menu but didn't have time to implement it.

The idea, of the left are (which contains the samples menu for now), is later we can add others widgets in it like one to add package to the project, settings area etc.

The navbar component of Fulma, is limited IMO.

The idea is to make the `Sidebar.fs` provide the support for the card element (title + collapsible state support) and provide the content via another widget to share code.
