### ISSUE TITLE
Better syntax highlighting

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/repl-legacy#17]
Right now we're using Monaco's default syntax highlighting for F# but it's not very good. @Krzysztof-Cieslak I guess Ionide is using a custom one? How is that done, with regular expressions? Can that be adapted to Monaco?

**Comment by MangelMaxime** [comment]
Ionide is using https://github.com/ionide/ionide-fsgrammar project. And the grammar are added via the [package.json](https://github.com/ionide/ionide-vscode-fsharp/blob/master/release/package.json#L48-L68) file. 

I think, I saw something in the Monaco API to add custom syntax support.

**Comment by MangelMaxime** [comment]
We can't use the ionide-fsgrammar in the REPL.

The library used to parsed the grammar isn't performant enough in the browser and so Monaco is using [monarch](https://microsoft.github.io/monaco-editor/monarch.html). 

I don't plan to implement another grammar for now. So I think we can close it for now.
