### ISSUE TITLE
Collapsible samples experience is weird

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/repl-legacy#24]
This is really weird to have a panel to show/hide like that. Why remove the previous layout ?

Also, we will need to have the left menu in future to set settings, load extra packages, add a small about info if we want etc. The left menu, in my mind is a place to add any "widget" we want in the future. 

The other solution would be to use modal, via the navbar etc. but then we will just end with a bunch of window, and hide the editor part.

If the left menu is really a problem, we can make it hide/show in a much nicer way. Something like what we do on mobile, when we slide left to right on the screen the menu is shown on some applications.

**Comment by alfonsogarciacaro** [comment]
In my 13-inch laptop the left menu was taking a lot of space so I really think user needs to be able to hide it somehow. I'd rather avoid modals but I'm OK with a more elegant way to hide/show it. The button in the navbar is just the fastest way I could think of to solve the problem :)

**Comment by voronoipotato** [comment]
Could you perhaps draw up a wireframe of the solution @MangelMaxime?

**Comment by MangelMaxime** [comment]
I will try to make a wireframe :)

But to be fair, I think it's will be easier to create a PR as it's just a really small change in my head. And discuss it with a gif showing the change in action :)

Edit: Small change in code speaking. But wireframe is harder for me :D

**Comment by alfonsogarciacaro** [comment]
That's the awesomeness of Fulma: it's easier to implement the UI directly than drafting a wireframe :wink:
