### ISSUE TITLE
Integration with Monaco

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/repl-legacy#3]
Sorry, @ncave, what's the status of this repo? I see there're some files taken from ionide-web, but they still seem to rely on communication with an independent FSharpAutoComplete process (running on .NET) to get autocompletion information, etc

IIRC you told me once you made the FSAC parts needed to make everything runnable in the browser compilable by Fable. Is this somewhere? Or can the information (e.g. `CompletionResult`) be obtained directly from FSC?

**UPDATE**: Looking at FSAC code, it seems it's just [a thin layer on top of FCS](https://github.com/fsharp/FsAutoComplete/blob/e5095da2b18da6fb6eb2fe7a9355d36e2fae9bf7/src/FsAutoComplete.Core/CommandResponse.fs#L406-L415) to provide a CLI or HTTP (with the Suave server) API. So I guess I can answer myself that yes, the information can be retrieved directly from FCS :wink:

**Comment by ncave** [comment]
@alfonsogarciacaro The status is unchanged (with the exception of updating the Monaco bindings to latest). Some FCS features have been available for integration for quite a long time (e.g. [here](https://github.com/ncave/FSharp.Compiler.Service/blob/fable/fcs/fcs-fable/test/app.fs#L69-L79)). It should be relatively easy to make some initial progress with basic functionality, if one has the time. Let me know if additional FCS features are needed.

**Comment by alfonsogarciacaro** [comment]
OMG, this is working!!! (sort of)

![image](https://user-images.githubusercontent.com/8275461/30511394-19959c08-9ad8-11e7-89f6-8b27b83aba09.png)

The only problem is I'm getting too many completion results. @ncave do you have any idea how to restrict them? The most relevant parts of the code are [the editor completion request](https://github.com/fable-compiler/fable-repl/blob/d90f785d621bb5d8ff183a8cedc5644ee0ef6a04/src/editor.fs#L217-L232) and the [FCS helper](https://github.com/fable-compiler/fable-repl/blob/d90f785d621bb5d8ff183a8cedc5644ee0ef6a04/src/fcs.fs#L25-L27) (the latter is basically what you had, looks like some of the parameters need to be more specific).

BTW, there's something I need to fix in Fable to make this work, I'll push it now.

**Comment by ncave** [comment]
@alfonsogarciacaro Looking in FSAC, you can pass a [filter](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/CompilerServiceInterface.fs#L135-L141) (either `StartsWith` or `Contains`) to narrow down declarations based on residue. You can also pass a [flag](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/Commands.fs#L207) to add [keywords](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/CommandResponse.fs#L406-L415) to the autocomplete list.

**Comment by alfonsogarciacaro** [comment]
TOTAL AWESOMENESS!!!

![image](https://user-images.githubusercontent.com/8275461/30512631-3fb278cc-9af4-11e7-9d20-6f22c4149301.png)

![image](https://user-images.githubusercontent.com/8275461/30512643-6a085dbc-9af4-11e7-9556-7e6de7887b2a.png)

**Comment by StachuDotNet** [comment]
Woah. Keep going!! :)

**Comment by alfonsogarciacaro** [comment]
@StachuDotNet You didn't see this, this is top secret :wink:
