### ISSUE TITLE
repl-legacy should not redirect to repl

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/repl-legacy#43]
@alfonsogarciacaro If we try to access http://fable.io/repl-legacy/ we are redirected to http://fable.io/repl.

We should keep access to http://fable.io/repl-legacy/ so people using Fable 1 can still use it.

**Comment by alfonsogarciacaro** [comment]
Good point! There's no possibility of confusion now, so I dropped the commit for the redirect :+1:
