### ISSUE TITLE
Can't build the repo with latest version of Fable (master)

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/repl-legacy#6]
@alfonsogarciacaro @ncave 

I am moving the discussion I started in this PR https://github.com/fable-compiler/Fable/pull/1209

Today, I wanted to build the repl again to add new features. First, when trying to build it I was having:

> error FABLE: Cannot find replacement for Char.isLetter

So I added, it. Then, I tryied to build it again with the version coming from this PR https://github.com/fable-compiler/Fable/pull/1209

And now, I get:

> fable: Compiled ..\FSharp.Compiler.Service_fable\fcs\fcs-fable\service_shim.fs
[!] (fable plugin) Error: C:/Projects/FSharp.Compiler.Service_fable/src/fsharp/tast.fs(3210,148): (3210,161) error FABLE: Cannot find replacement for Microsoft.FSharp.Core.PrintfModule::PrintFormatToStringThen

I added some log, and I know that sometimes it go there: https://github.com/fable-compiler/Fable/blob/master/src/dotnet/Fable.Compiler/Replacements.fs#L910-L915

So, I don't understand why it's falling in this case. Any idea ?

**Comment by ncave** [comment]
@MangelMaxime This should be fixed now if you get all FCS latest and use latest Fable.

**Comment by ncave** [comment]
@MangelMaxime Also, netcore 1.0 is no longer needed, just 2.0.

**Comment by MangelMaxime** [comment]
Thanks you @ncave I will test it
